//==============================================================================
// Copyright (c) 2015 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  THIS CODE WAS AUTOGENERATED BY PASSTHROUGHGENERATOR ON 07/22/15
//==============================================================================

#ifndef DX12CORESYMBOLSERIALIZERS_H
#define DX12CORESYMBOLSERIALIZERS_H

#include "DX12Defines.h"


namespace DX12CoreSerializers
{

const char* WriteCommandListTypeEnumAsString(DWORD inWriteCommandListTypeEnumAsString);
const char* WriteCommandQueueFlagsEnumAsString(DWORD inWriteCommandQueueFlagsEnumAsString);
void DecomposeCommandQueueFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteCommandQueuePriorityEnumAsString(DWORD inWriteCommandQueuePriorityEnumAsString);
const char* WritePrimitiveTopologyTypeEnumAsString(DWORD inWritePrimitiveTopologyTypeEnumAsString);
const char* WriteInputClassificationEnumAsString(DWORD inWriteInputClassificationEnumAsString);
const char* WriteFillModeEnumAsString(DWORD inWriteFillModeEnumAsString);
const char* WriteCullModeEnumAsString(DWORD inWriteCullModeEnumAsString);
const char* WriteComparisonFuncEnumAsString(DWORD inWriteComparisonFuncEnumAsString);
const char* WriteDepthWriteMaskEnumAsString(DWORD inWriteDepthWriteMaskEnumAsString);
const char* WriteStencilOpEnumAsString(DWORD inWriteStencilOpEnumAsString);
const char* WriteBlendEnumAsString(DWORD inWriteBlendEnumAsString);
const char* WriteBlendOpEnumAsString(DWORD inWriteBlendOpEnumAsString);
const char* WriteColorWriteEnableEnumAsString(DWORD inWriteColorWriteEnableEnumAsString);
const char* WriteLogicOpEnumAsString(DWORD inWriteLogicOpEnumAsString);
const char* WriteConservativeRasterizationModeEnumAsString(DWORD inWriteConservativeRasterizationModeEnumAsString);
const char* WriteIndexBufferStripCutValueEnumAsString(DWORD inWriteIndexBufferStripCutValueEnumAsString);
const char* WritePipelineStateFlagsEnumAsString(DWORD inWritePipelineStateFlagsEnumAsString);
void DecomposePipelineStateFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteFeatureEnumAsString(DWORD inWriteFeatureEnumAsString);
const char* WriteShaderMinPrecisionSupportEnumAsString(DWORD inWriteShaderMinPrecisionSupportEnumAsString);
const char* WriteTiledResourcesTierEnumAsString(DWORD inWriteTiledResourcesTierEnumAsString);
const char* WriteResourceBindingTierEnumAsString(DWORD inWriteResourceBindingTierEnumAsString);
const char* WriteConservativeRasterizationTierEnumAsString(DWORD inWriteConservativeRasterizationTierEnumAsString);
const char* WriteFormatSupport1EnumAsString(DWORD inWriteFormatSupport1EnumAsString);
const char* WriteFormatSupport2EnumAsString(DWORD inWriteFormatSupport2EnumAsString);
const char* WriteMultisampleQualityLevelFlagsEnumAsString(DWORD inWriteMultisampleQualityLevelFlagsEnumAsString);
void DecomposeMultisampleQualityLevelFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteCrossNodeSharingTierEnumAsString(DWORD inWriteCrossNodeSharingTierEnumAsString);
const char* WriteResourceHeapTierEnumAsString(DWORD inWriteResourceHeapTierEnumAsString);
const char* WriteHeapTypeEnumAsString(DWORD inWriteHeapTypeEnumAsString);
const char* WriteCpuPagePropertyEnumAsString(DWORD inWriteCpuPagePropertyEnumAsString);
const char* WriteMemoryPoolEnumAsString(DWORD inWriteMemoryPoolEnumAsString);
const char* WriteHeapFlagsEnumAsString(DWORD inWriteHeapFlagsEnumAsString);
void DecomposeHeapFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteResourceDimensionEnumAsString(DWORD inWriteResourceDimensionEnumAsString);
const char* WriteTextureLayoutEnumAsString(DWORD inWriteTextureLayoutEnumAsString);
const char* WriteResourceFlagsEnumAsString(DWORD inWriteResourceFlagsEnumAsString);
void DecomposeResourceFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteTileRangeFlagsEnumAsString(DWORD inWriteTileRangeFlagsEnumAsString);
void DecomposeTileRangeFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteTileMappingFlagsEnumAsString(DWORD inWriteTileMappingFlagsEnumAsString);
void DecomposeTileMappingFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteTileCopyFlagsEnumAsString(DWORD inWriteTileCopyFlagsEnumAsString);
void DecomposeTileCopyFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteResourceStatesEnumAsString(DWORD inWriteResourceStatesEnumAsString);
const char* WriteResourceBarrierTypeEnumAsString(DWORD inWriteResourceBarrierTypeEnumAsString);
const char* WriteResourceBarrierFlagsEnumAsString(DWORD inWriteResourceBarrierFlagsEnumAsString);
void DecomposeResourceBarrierFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteTextureCopyTypeEnumAsString(DWORD inWriteTextureCopyTypeEnumAsString);
const char* WriteShaderComponentMappingEnumAsString(DWORD inWriteShaderComponentMappingEnumAsString);
const char* WriteBufferSrvFlagsEnumAsString(DWORD inWriteBufferSrvFlagsEnumAsString);
void DecomposeBufferSrvFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteSrvDimensionEnumAsString(DWORD inWriteSrvDimensionEnumAsString);
const char* WriteFilterEnumAsString(DWORD inWriteFilterEnumAsString);
const char* WriteFilterTypeEnumAsString(DWORD inWriteFilterTypeEnumAsString);
const char* WriteFilterReductionTypeEnumAsString(DWORD inWriteFilterReductionTypeEnumAsString);
const char* WriteTextureAddressModeEnumAsString(DWORD inWriteTextureAddressModeEnumAsString);
const char* WriteBufferUavFlagsEnumAsString(DWORD inWriteBufferUavFlagsEnumAsString);
void DecomposeBufferUavFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteUavDimensionEnumAsString(DWORD inWriteUavDimensionEnumAsString);
const char* WriteRtvDimensionEnumAsString(DWORD inWriteRtvDimensionEnumAsString);
const char* WriteDsvFlagsEnumAsString(DWORD inWriteDsvFlagsEnumAsString);
void DecomposeDsvFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteDsvDimensionEnumAsString(DWORD inWriteDsvDimensionEnumAsString);
const char* WriteClearFlagsEnumAsString(DWORD inWriteClearFlagsEnumAsString);
void DecomposeClearFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteFenceFlagsEnumAsString(DWORD inWriteFenceFlagsEnumAsString);
void DecomposeFenceFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteDescriptorHeapTypeEnumAsString(DWORD inWriteDescriptorHeapTypeEnumAsString);
const char* WriteDescriptorHeapFlagsEnumAsString(DWORD inWriteDescriptorHeapFlagsEnumAsString);
void DecomposeDescriptorHeapFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteDescriptorRangeTypeEnumAsString(DWORD inWriteDescriptorRangeTypeEnumAsString);
const char* WriteShaderVisibilityEnumAsString(DWORD inWriteShaderVisibilityEnumAsString);
const char* WriteRootParameterTypeEnumAsString(DWORD inWriteRootParameterTypeEnumAsString);
const char* WriteRootSignatureFlagsEnumAsString(DWORD inWriteRootSignatureFlagsEnumAsString);
void DecomposeRootSignatureFlagsEnumAsString(DWORD inFlags, gtASCIIString& ioFlagsString);
const char* WriteStaticBorderColorEnumAsString(DWORD inWriteStaticBorderColorEnumAsString);
const char* WriteQueryHeapTypeEnumAsString(DWORD inWriteQueryHeapTypeEnumAsString);
const char* WriteQueryTypeEnumAsString(DWORD inWriteQueryTypeEnumAsString);
const char* WritePredicationOpEnumAsString(DWORD inWritePredicationOpEnumAsString);
const char* WriteIndirectArgumentTypeEnumAsString(DWORD inWriteIndirectArgumentTypeEnumAsString);

gtASCIIString& WriteCommandQueueDescStructAsString(const D3D12_COMMAND_QUEUE_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteInputElementDescStructAsString(const D3D12_INPUT_ELEMENT_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteSoDeclarationEntryStructAsString(const D3D12_SO_DECLARATION_ENTRY inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteViewportStructAsString(const D3D12_VIEWPORT inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteBoxStructAsString(const D3D12_BOX inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDepthStencilopDescStructAsString(const D3D12_DEPTH_STENCILOP_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDepthStencilDescStructAsString(const D3D12_DEPTH_STENCIL_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRenderTargetBlendDescStructAsString(const D3D12_RENDER_TARGET_BLEND_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteBlendDescStructAsString(const D3D12_BLEND_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRasterizerDescStructAsString(const D3D12_RASTERIZER_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteShaderBytecodeStructAsString(const D3D12_SHADER_BYTECODE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteStreamOutputDescStructAsString(const D3D12_STREAM_OUTPUT_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteInputLayoutDescStructAsString(const D3D12_INPUT_LAYOUT_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteCachedPipelineStateStructAsString(const D3D12_CACHED_PIPELINE_STATE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteGraphicsPipelineStateDescStructAsString(const D3D12_GRAPHICS_PIPELINE_STATE_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteComputePipelineStateDescStructAsString(const D3D12_COMPUTE_PIPELINE_STATE_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureData_optionsStructAsString(const D3D12_FEATURE_DATA_D3D12_OPTIONS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureDataArchitectureStructAsString(const D3D12_FEATURE_DATA_ARCHITECTURE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureDataFeatureLevelsStructAsString(const D3D12_FEATURE_DATA_FEATURE_LEVELS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureDataFormatSupportStructAsString(const D3D12_FEATURE_DATA_FORMAT_SUPPORT inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureDataMultisampleQualityLevelsStructAsString(const D3D12_FEATURE_DATA_MULTISAMPLE_QUALITY_LEVELS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureDataFormatInfoStructAsString(const D3D12_FEATURE_DATA_FORMAT_INFO inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteFeatureDataGpuVirtualAddressSupportStructAsString(const D3D12_FEATURE_DATA_GPU_VIRTUAL_ADDRESS_SUPPORT inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteResourceAllocationInfoStructAsString(const D3D12_RESOURCE_ALLOCATION_INFO inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteHeapPropertiesStructAsString(const D3D12_HEAP_PROPERTIES inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteHeapDescStructAsString(const D3D12_HEAP_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteResourceDescStructAsString(const D3D12_RESOURCE_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDepthStencilValueStructAsString(const D3D12_DEPTH_STENCIL_VALUE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteClearValueStructAsString(const D3D12_CLEAR_VALUE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRangeStructAsString(const D3D12_RANGE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteSubresourceInfoStructAsString(const D3D12_SUBRESOURCE_INFO inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTiledResourceCoordinateStructAsString(const D3D12_TILED_RESOURCE_COORDINATE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTileRegionSizeStructAsString(const D3D12_TILE_REGION_SIZE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteSubresourceTilingStructAsString(const D3D12_SUBRESOURCE_TILING inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTileShapeStructAsString(const D3D12_TILE_SHAPE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WritePackedMipInfoStructAsString(const D3D12_PACKED_MIP_INFO inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteResourceTransitionBarrierStructAsString(const D3D12_RESOURCE_TRANSITION_BARRIER inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteResourceAliasingBarrierStructAsString(const D3D12_RESOURCE_ALIASING_BARRIER inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteResourceUavBarrierStructAsString(const D3D12_RESOURCE_UAV_BARRIER inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteResourceBarrierStructAsString(const D3D12_RESOURCE_BARRIER inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteSubresourceFootprintStructAsString(const D3D12_SUBRESOURCE_FOOTPRINT inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WritePlacedSubresourceFootprintStructAsString(const D3D12_PLACED_SUBRESOURCE_FOOTPRINT inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTextureCopyLocationStructAsString(const D3D12_TEXTURE_COPY_LOCATION inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteBufferSrvStructAsString(const D3D12_BUFFER_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dSrvStructAsString(const D3D12_TEX1D_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dArraySrvStructAsString(const D3D12_TEX1D_ARRAY_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dSrvStructAsString(const D3D12_TEX2D_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dArraySrvStructAsString(const D3D12_TEX2D_ARRAY_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex3dSrvStructAsString(const D3D12_TEX3D_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTexcubeSrvStructAsString(const D3D12_TEXCUBE_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTexcubeArraySrvStructAsString(const D3D12_TEXCUBE_ARRAY_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dmsSrvStructAsString(const D3D12_TEX2DMS_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dmsArraySrvStructAsString(const D3D12_TEX2DMS_ARRAY_SRV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteShaderResourceViewDescStructAsString(const D3D12_SHADER_RESOURCE_VIEW_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteConstantBufferViewDescStructAsString(const D3D12_CONSTANT_BUFFER_VIEW_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteSamplerDescStructAsString(const D3D12_SAMPLER_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteBufferUavStructAsString(const D3D12_BUFFER_UAV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dUavStructAsString(const D3D12_TEX1D_UAV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dArrayUavStructAsString(const D3D12_TEX1D_ARRAY_UAV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dUavStructAsString(const D3D12_TEX2D_UAV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dArrayUavStructAsString(const D3D12_TEX2D_ARRAY_UAV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex3dUavStructAsString(const D3D12_TEX3D_UAV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteUnorderedAccessViewDescStructAsString(const D3D12_UNORDERED_ACCESS_VIEW_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteBufferRtvStructAsString(const D3D12_BUFFER_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dRtvStructAsString(const D3D12_TEX1D_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dArrayRtvStructAsString(const D3D12_TEX1D_ARRAY_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dRtvStructAsString(const D3D12_TEX2D_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dmsRtvStructAsString(const D3D12_TEX2DMS_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dArrayRtvStructAsString(const D3D12_TEX2D_ARRAY_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dmsArrayRtvStructAsString(const D3D12_TEX2DMS_ARRAY_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex3dRtvStructAsString(const D3D12_TEX3D_RTV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRenderTargetViewDescStructAsString(const D3D12_RENDER_TARGET_VIEW_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dDsvStructAsString(const D3D12_TEX1D_DSV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex1dArrayDsvStructAsString(const D3D12_TEX1D_ARRAY_DSV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dDsvStructAsString(const D3D12_TEX2D_DSV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dArrayDsvStructAsString(const D3D12_TEX2D_ARRAY_DSV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dmsDsvStructAsString(const D3D12_TEX2DMS_DSV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteTex2dmsArrayDsvStructAsString(const D3D12_TEX2DMS_ARRAY_DSV inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDepthStencilViewDescStructAsString(const D3D12_DEPTH_STENCIL_VIEW_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDescriptorHeapDescStructAsString(const D3D12_DESCRIPTOR_HEAP_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDescriptorRangeStructAsString(const D3D12_DESCRIPTOR_RANGE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRootDescriptorTableStructAsString(const D3D12_ROOT_DESCRIPTOR_TABLE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRootConstantsStructAsString(const D3D12_ROOT_CONSTANTS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRootDescriptorStructAsString(const D3D12_ROOT_DESCRIPTOR inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRootParameterStructAsString(const D3D12_ROOT_PARAMETER inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteStaticSamplerDescStructAsString(const D3D12_STATIC_SAMPLER_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteRootSignatureDescStructAsString(const D3D12_ROOT_SIGNATURE_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteCpuDescriptorHandleStructAsString(const D3D12_CPU_DESCRIPTOR_HANDLE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteGpuDescriptorHandleStructAsString(const D3D12_GPU_DESCRIPTOR_HANDLE inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDiscardRegionStructAsString(const D3D12_DISCARD_REGION inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteQueryHeapDescStructAsString(const D3D12_QUERY_HEAP_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteQueryDataPipelineStatisticsStructAsString(const D3D12_QUERY_DATA_PIPELINE_STATISTICS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteQueryDataSoStatisticsStructAsString(const D3D12_QUERY_DATA_SO_STATISTICS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteStreamOutputBufferViewStructAsString(const D3D12_STREAM_OUTPUT_BUFFER_VIEW inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDrawArgumentsStructAsString(const D3D12_DRAW_ARGUMENTS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDrawIndexedArgumentsStructAsString(const D3D12_DRAW_INDEXED_ARGUMENTS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteDispatchArgumentsStructAsString(const D3D12_DISPATCH_ARGUMENTS inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteVertexBufferViewStructAsString(const D3D12_VERTEX_BUFFER_VIEW inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteIndexBufferViewStructAsString(const D3D12_INDEX_BUFFER_VIEW inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteIndirectArgumentDescStructAsString(const D3D12_INDIRECT_ARGUMENT_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteCommandSignatureDescStructAsString(const D3D12_COMMAND_SIGNATURE_DESC inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteSubresourceDataStructAsString(const D3D12_SUBRESOURCE_DATA inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);
gtASCIIString& WriteMemcpyDestStructAsString(const D3D12_MEMCPY_DEST inStruct, gtASCIIString& ioSerializedStructure, const char* inOptionalNameAttribute = NULL);


};


#endif // DX12CORESYMBOLSERIALIZERS_H

