//=====================================================================
//
/// \author GPU Developer Tools
//
// StringifyDxgiTypeEnums.h
// This file is autogenerated
//
//=====================================================================
//
// Last checkin:  $DateTime: 2015/12/08 13:22:59 $
// Last edited by: $Author: gselley $
//=====================================================================
//   (c) 2013 Advanced Micro Devices, Inc.
//=====================================================================
#ifndef STRINGIFYDXGITYPEENUMS_H
#define STRINGIFYDXGITYPEENUMS_H

#include "dxgi.h"
#include "AMDTBaseTools/Include/gtASCIIString.h"

gtASCIIString Stringify_DXGI_MODE_SCANLINE_ORDER(DXGI_MODE_SCANLINE_ORDER var);
gtASCIIString Stringify_DXGI_MODE_SCALING(DXGI_MODE_SCALING var);
gtASCIIString Stringify_DXGI_MODE_ROTATION(DXGI_MODE_ROTATION var);
gtASCIIString Stringify_DXGI_SWAP_EFFECT(DXGI_SWAP_EFFECT var);

#endif /* STRINGIFYDXGITYPEENUMS_H */