//=====================================================================
//
/// \author GPU Developer Tools
//
// StringifyDxgiFormatEnums.h
// This file is autogenerated
//
//=====================================================================
//
// Last checkin:  $DateTime: 2015/12/08 13:22:59 $
// Last edited by: $Author: gselley $
//=====================================================================
//   (c) 2013 Advanced Micro Devices, Inc.
//=====================================================================
#ifndef STRINGIFYDXGIFORMATENUMS_H
#define STRINGIFYDXGIFORMATENUMS_H

#include "dxgiformat.h"
#include "AMDTBaseTools/Include/gtASCIIString.h"

gtASCIIString Stringify_DXGI_FORMAT(DXGI_FORMAT var);

#endif /* STRINGIFYDXGIFORMATENUMS_H */